### PR TITLE
add info for 0x0402 type

### PR DESCRIPTION
**Pull request by BuXXe**

### CODE REVIEW

**Comment by Deltwin** [comment]
Are you sure that type is for **Version number** and not for **End Record**?

**Comment by BuXXe** [comment]
I guess you dont know who I am and what I do so I give this as proof :) : 
0x402 type
It inits the version with 0x100 as default value and then tries to read the 0x402 record. If the version number doesnt fit (0x102 in this case) it will error out with wrong database version.

**Comment by BuXXe** [comment]
Also added info to the texture data, mip map number entry (dont have a better name for it yet). The 0x10 entry gives the info that it is a bump map. A 0x02 adds the info that the bump map also contains luminance data (see ddraw.h DDPF_BUMPLUMINANCE). If you want further proof, look at functions F0x00436E20 and F0x00434260. In the first one, the texture data of the .txd files is read and interpreted. These values are translated to a different flags format which is used and interpreted by the second function. Here you can connect the flags with actual functionality by identifying the DDRAW constants. I can give more proofs but I hope this suffices for now.

**Comment by BuXXe** [comment]
I finally found some info for the strange 0x209 entries. During the model loading process, the first uint16 value is used as a record_id to find another model in the same database. Due to the fact that it is only uint16 the db_id entry is always 0 and therefor only models in the same database may be referenced. I cant tell what this model is used for yet but my first guess would be that the following float value could be a distance and then the model might be a LOD or alternate model depending on the distance to the player. But we will see about that in the future i hope :). If you need proof for this one, its pretty hard to give it right now as it relies on the knowledge about the loading of the models and the data structures involved. To give a short proof I can say that: the function which loads the models (F0x00424E80) will use the 0x209 entry at the end of it in order to call itself again.  ( the call is hidden behind the F0x00436DA0 function which helps with some folder connector stuff)
Unbenannt

**Comment by BuXXe** [comment]
I could proof my theory about the 0x209 entries that they are used to implement LOD behavior. Riot Engine Characters have the LOD info encoded in their character data entry. For Riot Engine Objects, this info is put into this separater 0x209 entry. 
final

**Comment by Zalasus** [comment]
Hey, thanks for the contribution! Some time ago I reworked the file format docs into a more structured, mdbook-based format. Hope I will get around to integrate your findings soon. Until I push that I will merge them into the old file.

Also, sorry it took so long for me to merge this. Working with private projects has been a bit difficult for me for some time, but I guess you figured that.

**Comment by BuXXe** [comment]
No worries, that way I could collect more stuff for a single merge. If you are interested in a little chat (we both are from germany as I have seen) just send me a msg for example via discord: buxxe

**Pull request merged**
